#!/usr/bin/env python3
"""Generate the first-paint pipeline mode catalog consumed by the browser."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from pipeline_mode_catalog import SCHEMA_VERSION, build_pipeline_mode_catalog  # noqa: E402


OUTPUT = ROOT / "backend" / "static" / "pipeline_mode_fallback.js"


def render_fallback() -> str:
    payload = {
        "schema_version": SCHEMA_VERSION,
        "modes": build_pipeline_mode_catalog(),
    }
    serialized = json.dumps(payload, ensure_ascii=False, indent=2)
    return (
        "// Generated by scripts/generate_pipeline_mode_fallback.py. Do not edit.\n"
        "(function () {\n"
        "    window.StockAgentUiPipelineModeFallback = "
        f"{serialized};\n"
        "})();\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the generated artifact is stale")
    args = parser.parse_args()

    expected = render_fallback()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"stale generated pipeline mode fallback: {OUTPUT}", file=sys.stderr)
            return 1
        print("pipeline mode fallback is up to date")
        return 0

    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"generated {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
